import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791400984828 implements MigrationInterface {
    name = 'InitialSchema1791400984828'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "mode_paiement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(30) NOT NULL, "libelle" character varying(100) NOT NULL, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d1aab0b3585d2fdc25209dda68f" UNIQUE ("code"), CONSTRAINT "PK_87e5968eb535b77fbad973c48e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "matricule" character varying(50) NOT NULL, "userId" uuid, "nomComplet" character varying(255) NOT NULL, "role" character varying(30) NOT NULL, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c0e005072cf74273d618b9dbd09" UNIQUE ("matricule"), CONSTRAINT "UQ_15baaa1eb6dd8d1f0a92a17d667" UNIQUE ("userId"), CONSTRAINT "PK_1000e989398c5d4ed585cf9a46f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."paiement_status_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "paiement" ("id_paiement" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying(255) NOT NULL, "status" "public"."paiement_status_enum" NOT NULL, "raison" character varying(255) NOT NULL, "montant" numeric(12,2), "modePaiementId" uuid, "canal" character varying(20), "agentId" uuid, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8f7e3de0c57b3553585ddff3e4" UNIQUE ("reference"), CONSTRAINT "CK_paiement_canal" CHECK ("canal" IS NULL OR "canal" IN ('BUREAU', 'TERRAIN')), CONSTRAINT "CK_paiement_montant_positif" CHECK ("montant" IS NULL OR "montant" >= 0), CONSTRAINT "PK_dfcbe2c7209228811aa3eed5e79" PRIMARY KEY ("id_paiement"))`);
        await queryRunner.query(`CREATE TABLE "paiement_location" ("id_paiement_location" uuid NOT NULL DEFAULT uuid_generate_v4(), "locationId" uuid NOT NULL, "nombre_paye" integer NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT now(), "date_fin" TIMESTAMP NOT NULL DEFAULT now(), "date_paiement" TIMESTAMP NOT NULL DEFAULT now(), "montant_paye" integer NOT NULL, "paiementId" uuid, CONSTRAINT "PK_8fe58eaa70db5488689706654f7" PRIMARY KEY ("id_paiement_location"))`);
        await queryRunner.query(`CREATE TABLE "activite_commerciale" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "libelle" jsonb NOT NULL, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5c563cd1c4389fbdb2440727b4e" UNIQUE ("code"), CONSTRAINT "PK_71edbbc2ddb0998bbd7ebf066fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commercant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "nif" character varying(10), "activiteId" uuid, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_affaa8611b05a85c298bd838a86" UNIQUE ("userId"), CONSTRAINT "PK_5bcd7aaece4e6bee7503f75c529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."location_periodicite_enum" AS ENUM('JOURNALIER', 'MENSUEL')`);
        await queryRunner.query(`CREATE TABLE "location" ("id_location" uuid NOT NULL DEFAULT uuid_generate_v4(), "periodicite" "public"."location_periodicite_enum" NOT NULL DEFAULT 'MENSUEL', "id_user" uuid NOT NULL, "nif" character varying(10) NOT NULL, "commercantId" uuid, "date_debut_loc" date NOT NULL, "date_fin_loc" date NOT NULL, "frequence" integer, "usage" character varying, "localId" uuid NOT NULL, CONSTRAINT "CK_location_dates_coherentes" CHECK ("date_debut_loc" <= "date_fin_loc"), CONSTRAINT "PK_e16e95dc8d528758443815aebf8" PRIMARY KEY ("id_location"))`);
        await queryRunner.query(`CREATE TYPE "public"."type_locale_type_contrat_enum" AS ENUM('JOURNALIER', 'ANNUEL')`);
        await queryRunner.query(`CREATE TABLE "type_locale" ("id_type_local" uuid NOT NULL DEFAULT uuid_generate_v4(), "municipalityId" character varying NOT NULL, "typeLoc" jsonb NOT NULL, "type_contrat" "public"."type_locale_type_contrat_enum" NOT NULL DEFAULT 'ANNUEL', "longueur" integer NOT NULL, "largeur" integer NOT NULL, "description" jsonb, "tarif" integer NOT NULL, CONSTRAINT "PK_485d6dad0d2c1834a8035fb4ea0" PRIMARY KEY ("id_type_local"))`);
        await queryRunner.query(`CREATE TYPE "public"."local_statut_enum" AS ENUM('DISPONIBLE', 'LOUE', 'INDISPONIBLE')`);
        await queryRunner.query(`CREATE TABLE "local" ("id_local" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero" character varying(11) NOT NULL, "statut" "public"."local_statut_enum" NOT NULL DEFAULT 'DISPONIBLE', "zoneId" uuid NOT NULL, "typelocalId" uuid NOT NULL, "latitude" numeric(12,6) NOT NULL, "longitude" numeric(12,6) NOT NULL, "rotation" numeric(5,2) NOT NULL, "date_derniere_scan" date, CONSTRAINT "PK_3af3f9a26d7319443f58117cc16" PRIMARY KEY ("id_local"))`);
        await queryRunner.query(`CREATE TABLE "distribution_zone" ("id_distribution_zone" uuid NOT NULL DEFAULT uuid_generate_v4(), "id_user" uuid NOT NULL, "zoneId" uuid NOT NULL, "status" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_041a8ba8a0d7b53d3a5eef10a26" PRIMARY KEY ("id_distribution_zone"))`);
        await queryRunner.query(`CREATE TABLE "commune" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codeExt" character varying(100) NOT NULL, "nom" character varying(255), "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_425a87816831102c0e049d53b6a" UNIQUE ("codeExt"), CONSTRAINT "PK_bc512eb8412b43c9dc6e2c9e683" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "marche" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "communeId" uuid NOT NULL, "nom" character varying(255) NOT NULL, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03bea016562547b5c8275a2c180" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_marche_commune_nom" ON "marche" ("communeId", "nom") `);
        await queryRunner.query(`CREATE TABLE "zone" ("id_zone" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying(50) NOT NULL, "status" boolean NOT NULL DEFAULT true, "formatted_id" character varying NOT NULL, "municipalityId" character varying NOT NULL, "marcheId" uuid, "delimitation" geometry(Polygon,4326) NOT NULL, CONSTRAINT "UQ_bbfd7da642e340e3397ea5fb7d1" UNIQUE ("nom"), CONSTRAINT "PK_9d9ce9ba474401ce6d856737be1" PRIMARY KEY ("id_zone"))`);
        await queryRunner.query(`CREATE TYPE "public"."sigrnf_sync_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "sigrnf_sync" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventType" character varying(100) NOT NULL, "localReference" character varying(255) NOT NULL, "status" "public"."sigrnf_sync_status_enum" NOT NULL DEFAULT 'PENDING', "attemptCount" integer NOT NULL DEFAULT '0', "lastAttemptAt" TIMESTAMP, "sentAt" TIMESTAMP, "responseReference" character varying(255), "errorMessage" text, "payload" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3766eb067d1dfe0422c2d98f789" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_sigrnf_sync_event_reference" ON "sigrnf_sync" ("eventType", "localReference") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id_notification" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying(100), "message" text, "data" jsonb, "isRead" boolean NOT NULL DEFAULT false, "priority" "public"."notification_priority_enum" NOT NULL DEFAULT 'MEDIUM', "channels" jsonb NOT NULL DEFAULT '{"inApp":true,"email":false,"sms":false}', "scheduledAt" TIMESTAMP, "sentAt" TIMESTAMP DEFAULT now(), "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5eeade67aa70b7db4a6bdd4dcd8" PRIMARY KEY ("id_notification"))`);
        await queryRunner.query(`CREATE TABLE "periodicite" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(20) NOT NULL, "libelle" character varying(100) NOT NULL, "unite" character varying(10) NOT NULL, "nbUnites" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_03e97761a6787ab9396c107e85f" UNIQUE ("code"), CONSTRAINT "CK_periodicite_unite" CHECK ("unite" IN ('JOUR', 'SEMAINE', 'MOIS', 'ANNEE')), CONSTRAINT "CK_periodicite_unites" CHECK ("nbUnites" > 0), CONSTRAINT "PK_f3c06a987681ca02aed1c01884d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_droit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "libelle" jsonb NOT NULL, "periodiciteId" uuid NOT NULL, "portee" character varying(20) NOT NULL, "peutPayerPartiel" boolean, "actif" boolean NOT NULL DEFAULT true, "description" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e63bb7bc868a55f68d7152517ed" UNIQUE ("code"), CONSTRAINT "PK_3fefcdd41ebe20ca2d180bc28a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tarif" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "typeDroitId" uuid NOT NULL, "periodiciteId" uuid, "typelocalId" uuid, "zoneId" uuid, "marcheId" uuid, "localId" uuid, "activiteId" uuid, "convention" character varying(255), "montant" numeric(12,2) NOT NULL, "devise" character varying(3), "dateDebut" date NOT NULL, "dateFin" date, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_tarif_dates" CHECK ("dateFin" IS NULL OR "dateDebut" <= "dateFin"), CONSTRAINT "CK_tarif_montant_positif" CHECK ("montant" >= 0), CONSTRAINT "CK_tarif_portee" CHECK ("typelocalId" IS NOT NULL OR "zoneId" IS NOT NULL OR "marcheId" IS NOT NULL OR "localId" IS NOT NULL OR "activiteId" IS NOT NULL), CONSTRAINT "PK_e0032bad5ceec96efad86c45944" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_tarif_dates" ON "tarif" ("dateDebut", "dateFin") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_periodicite" ON "tarif" ("periodiciteId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_activite" ON "tarif" ("activiteId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_typelocal" ON "tarif" ("typelocalId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_local" ON "tarif" ("localId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_marche" ON "tarif" ("marcheId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_zone" ON "tarif" ("zoneId") `);
        await queryRunner.query(`CREATE INDEX "IX_tarif_droit" ON "tarif" ("typeDroitId") `);
        await queryRunner.query(`CREATE TABLE "echeance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "locationId" uuid NOT NULL, "commercantId" uuid NOT NULL, "typeDroitId" uuid NOT NULL, "periodeDebut" date NOT NULL, "periodeFin" date NOT NULL, "dateEcheance" date NOT NULL, "montantTheorique" numeric(12,2) NOT NULL, "statut" character varying(30) NOT NULL, "source" character varying(20) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_echeance_source" CHECK ("source" IN ('AUTO', 'MANUEL')), CONSTRAINT "CK_echeance_statut" CHECK ("statut" IN ('PLANIFIEE', 'PARTIELLE', 'PAYEE', 'EN_RETARD', 'ANNULEE')), CONSTRAINT "CK_echeance_dates" CHECK ("periodeDebut" <= "periodeFin"), CONSTRAINT "CK_echeance_montant_theorique" CHECK ("montantTheorique" >= 0), CONSTRAINT "PK_b916882d3396522c88254529500" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_echeance_periode" ON "echeance" ("locationId", "typeDroitId", "periodeDebut", "periodeFin") `);
        await queryRunner.query(`CREATE TABLE "redevance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "echeanceId" uuid, "locationId" uuid, "commercantId" uuid NOT NULL, "montantDu" numeric(12,2) NOT NULL, "montantRegle" numeric(12,2) NOT NULL DEFAULT '0', "statut" character varying(30) NOT NULL, "dateOuverture" date NOT NULL, "dateCloture" date, "motif" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d3a1cc96631a07a15638cb30288" UNIQUE ("echeanceId"), CONSTRAINT "CK_redevance_statut" CHECK ("statut" IN ('OUVERTE', 'PARTIELLE', 'SOLDEE', 'ANNULEE')), CONSTRAINT "CK_redevance_dates" CHECK ("dateCloture" IS NULL OR "dateOuverture" <= "dateCloture"), CONSTRAINT "CK_redevance_montants" CHECK ("montantDu" >= 0 AND "montantRegle" >= 0 AND "montantRegle" <= "montantDu"), CONSTRAINT "PK_1e4dd003a4dd7a610972fed2441" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recette" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paiementId" uuid NOT NULL, "dateRecette" date NOT NULL, "montant" numeric(12,2) NOT NULL, "modePaiementId" uuid, "canal" character varying(20), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e7336902897fad254482f7ba731" UNIQUE ("paiementId"), CONSTRAINT "CK_recette_canal" CHECK ("canal" IS NULL OR "canal" IN ('BUREAU', 'TERRAIN')), CONSTRAINT "CK_recette_montant" CHECK ("montant" >= 0), CONSTRAINT "PK_2e3debb3047f8e82ab71e4eb2f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quittance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero" character varying(50) NOT NULL, "paiementId" uuid NOT NULL, "montant" numeric(12,2) NOT NULL, "dateEmission" TIMESTAMP NOT NULL, "statut" character varying(30) NOT NULL, "agentId" uuid, "documentUrl" character varying(500), "qrToken" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c09ea1a480de092db8cf4460faf" UNIQUE ("numero"), CONSTRAINT "UQ_3f3908ae878466f22b0f26ebcff" UNIQUE ("paiementId"), CONSTRAINT "CK_quittance_statut" CHECK ("statut" IN ('EMISE', 'ANNULEE', 'REMPLACEE')), CONSTRAINT "CK_quittance_montant" CHECK ("montant" >= 0), CONSTRAINT "PK_a3b8bca389cbcc49ddcab31bbf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "presence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "commercantId" uuid NOT NULL, "datePresence" date NOT NULL, "zoneId" uuid NOT NULL, "localId" uuid, "source" character varying(30) NOT NULL, "horodatage" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0088b38d7cf2dc6ad815d33e7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_presence_zone_date" ON "presence" ("zoneId", "datePresence") `);
        await queryRunner.query(`CREATE INDEX "IX_presence_commercant_date" ON "presence" ("commercantId", "datePresence") `);
        await queryRunner.query(`CREATE TABLE "parametre" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cle" character varying(100) NOT NULL, "portee" character varying(20) NOT NULL, "scopeId" character varying(50) NOT NULL DEFAULT '', "valeur" jsonb NOT NULL, "description" character varying(500), "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ac405f8e478dca9c82490c6a2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_parametre_cle_portee_scope" ON "parametre" ("cle", "portee", "scopeId") `);
        await queryRunner.query(`CREATE TABLE "paiement_redevance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paiementId" uuid NOT NULL, "redevanceId" uuid NOT NULL, "montantImpute" numeric(12,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_paiement_redevance_montant" CHECK ("montantImpute" > 0), CONSTRAINT "PK_cbf6810fd0bd248ef75e7a512a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_paiement_redevance" ON "paiement_redevance" ("paiementId", "redevanceId") `);
        await queryRunner.query(`CREATE TABLE "controle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agentId" uuid NOT NULL, "dateControle" TIMESTAMP NOT NULL, "zoneId" uuid NOT NULL, "localId" uuid, "commercantId" uuid, "presenceId" uuid, "typeAnomalie" character varying(50), "observations" text, "statut" character varying(30), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_controle_statut" CHECK ("statut" IS NULL OR "statut" IN ('OUVERT', 'CLOTURE')), CONSTRAINT "PK_aa154e891e1fcc529d252470f99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tableName" character varying(100) NOT NULL, "recordId" uuid NOT NULL, "action" character varying(20) NOT NULL, "acteurId" uuid, "ancienEtat" jsonb, "nouvelEtat" jsonb, "ip" character varying(64), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_audit_log_action" CHECK ("action" IN ('CREATION', 'MODIFICATION', 'SUPPRESSION')), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_audit_log_created" ON "audit_log" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IX_audit_log_table_record" ON "audit_log" ("tableName", "recordId") `);
        await queryRunner.query(`CREATE TABLE "affectation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "commercantId" uuid NOT NULL, "localId" uuid NOT NULL, "dateDebut" date NOT NULL, "dateFin" date, "statut" character varying(20) NOT NULL DEFAULT 'ACTIVE', "motif" character varying(255), "montantTheoriqueMensuel" numeric(12,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CK_affectation_statut" CHECK ("statut" IN ('ACTIVE', 'TERMINEE', 'RESILIEE')), CONSTRAINT "CK_affectation_dates" CHECK ("dateFin" IS NULL OR "dateDebut" <= "dateFin"), CONSTRAINT "CK_affectation_montant" CHECK ("montantTheoriqueMensuel" IS NULL OR "montantTheoriqueMensuel" >= 0), CONSTRAINT "PK_dd9c6af8306b9c2d9da3eebf555" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_affectation_commercant" ON "affectation" ("commercantId") `);
        await queryRunner.query(`CREATE INDEX "IX_affectation_local" ON "affectation" ("localId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_affectation_commercant_local_debut" ON "affectation" ("commercantId", "localId", "dateDebut") `);
        await queryRunner.query(`ALTER TABLE "paiement" ADD CONSTRAINT "FK_fe61685939535671e26808d848e" FOREIGN KEY ("modePaiementId") REFERENCES "mode_paiement"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement" ADD CONSTRAINT "FK_b007bba65d9f9c530719a2e9917" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement_location" ADD CONSTRAINT "FK_e9dacf4b263bba19661503c6467" FOREIGN KEY ("locationId") REFERENCES "location"("id_location") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement_location" ADD CONSTRAINT "FK_06ba8fa8cfc78122d47e69d6ace" FOREIGN KEY ("paiementId") REFERENCES "paiement"("id_paiement") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commercant" ADD CONSTRAINT "FK_52298195bfa471ebb106a372205" FOREIGN KEY ("activiteId") REFERENCES "activite_commerciale"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_42047a721a672b9bb58bab4e4c0" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_313ee835847f09171f2388edfd7" FOREIGN KEY ("localId") REFERENCES "local"("id_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "local" ADD CONSTRAINT "FK_4e8523a7a7be0e4c8f0f8d87483" FOREIGN KEY ("zoneId") REFERENCES "zone"("id_zone") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "local" ADD CONSTRAINT "FK_7dc68186f210b336ef0729e8f00" FOREIGN KEY ("typelocalId") REFERENCES "type_locale"("id_type_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distribution_zone" ADD CONSTRAINT "FK_14be07e38224a638d1e6817970f" FOREIGN KEY ("zoneId") REFERENCES "zone"("id_zone") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marche" ADD CONSTRAINT "FK_0c7a38243b5e2e1c0d8691b6d85" FOREIGN KEY ("communeId") REFERENCES "commune"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zone" ADD CONSTRAINT "FK_2fb8e047bb273972f5b2b3fff0f" FOREIGN KEY ("marcheId") REFERENCES "marche"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type_droit" ADD CONSTRAINT "FK_2c9503133131d84c7d03c88a639" FOREIGN KEY ("periodiciteId") REFERENCES "periodicite"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_51247cc1b452e66fce38d16b315" FOREIGN KEY ("typeDroitId") REFERENCES "type_droit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_955abfa6affa003c4089bb758bc" FOREIGN KEY ("periodiciteId") REFERENCES "periodicite"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_eface4ddda53819e035e0fe3d0b" FOREIGN KEY ("typelocalId") REFERENCES "type_locale"("id_type_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_f6f64961aef6a951a955440b251" FOREIGN KEY ("zoneId") REFERENCES "zone"("id_zone") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_036009d041bb77a3cb22ccfb885" FOREIGN KEY ("marcheId") REFERENCES "marche"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_333bf7319119e9aaee9355bb599" FOREIGN KEY ("localId") REFERENCES "local"("id_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarif" ADD CONSTRAINT "FK_11b213ae69c7dcdeb03cf173300" FOREIGN KEY ("activiteId") REFERENCES "activite_commerciale"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD CONSTRAINT "FK_218b09df03e359e3cc13e724137" FOREIGN KEY ("locationId") REFERENCES "location"("id_location") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD CONSTRAINT "FK_e114bfbd4a9e15f84b44ca20cc4" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD CONSTRAINT "FK_27e2c16ce312e57b57534f2c9c3" FOREIGN KEY ("typeDroitId") REFERENCES "type_droit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redevance" ADD CONSTRAINT "FK_d3a1cc96631a07a15638cb30288" FOREIGN KEY ("echeanceId") REFERENCES "echeance"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redevance" ADD CONSTRAINT "FK_c58c9419e1f2fece73912b96983" FOREIGN KEY ("locationId") REFERENCES "location"("id_location") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redevance" ADD CONSTRAINT "FK_f71f211f9f369783c263f949383" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recette" ADD CONSTRAINT "FK_e7336902897fad254482f7ba731" FOREIGN KEY ("paiementId") REFERENCES "paiement"("id_paiement") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recette" ADD CONSTRAINT "FK_36c676f53129d6df971a4d8a5d3" FOREIGN KEY ("modePaiementId") REFERENCES "mode_paiement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quittance" ADD CONSTRAINT "FK_3f3908ae878466f22b0f26ebcff" FOREIGN KEY ("paiementId") REFERENCES "paiement"("id_paiement") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quittance" ADD CONSTRAINT "FK_6b50a171eb461487588a6373a5d" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presence" ADD CONSTRAINT "FK_74b42bd3588c31e1ba501245922" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presence" ADD CONSTRAINT "FK_86c761a5794b7ca87a49987d2ec" FOREIGN KEY ("zoneId") REFERENCES "zone"("id_zone") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presence" ADD CONSTRAINT "FK_11aec335fadcdd040b91b7e39d5" FOREIGN KEY ("localId") REFERENCES "local"("id_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement_redevance" ADD CONSTRAINT "FK_5b97f3e1b54a2de30841e3e2b55" FOREIGN KEY ("paiementId") REFERENCES "paiement"("id_paiement") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement_redevance" ADD CONSTRAINT "FK_e87bc00627bab8c715344b3e1ef" FOREIGN KEY ("redevanceId") REFERENCES "redevance"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controle" ADD CONSTRAINT "FK_d9e93acbeefb11de15f86290861" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controle" ADD CONSTRAINT "FK_6f2a63abb4a36a7f4437311702f" FOREIGN KEY ("zoneId") REFERENCES "zone"("id_zone") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controle" ADD CONSTRAINT "FK_6ef89e3d9a9f532657f23836952" FOREIGN KEY ("localId") REFERENCES "local"("id_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controle" ADD CONSTRAINT "FK_8cde4835296730f4a993b8db674" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "controle" ADD CONSTRAINT "FK_cefd31d0bd84d6c5d4b5f0c058b" FOREIGN KEY ("presenceId") REFERENCES "presence"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_528d4cdc16291dd956a3acd8316" FOREIGN KEY ("commercantId") REFERENCES "commercant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_909be5dafdf18fdba1c47584e2c" FOREIGN KEY ("localId") REFERENCES "local"("id_local") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_909be5dafdf18fdba1c47584e2c"`);
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_528d4cdc16291dd956a3acd8316"`);
        await queryRunner.query(`ALTER TABLE "controle" DROP CONSTRAINT "FK_cefd31d0bd84d6c5d4b5f0c058b"`);
        await queryRunner.query(`ALTER TABLE "controle" DROP CONSTRAINT "FK_8cde4835296730f4a993b8db674"`);
        await queryRunner.query(`ALTER TABLE "controle" DROP CONSTRAINT "FK_6ef89e3d9a9f532657f23836952"`);
        await queryRunner.query(`ALTER TABLE "controle" DROP CONSTRAINT "FK_6f2a63abb4a36a7f4437311702f"`);
        await queryRunner.query(`ALTER TABLE "controle" DROP CONSTRAINT "FK_d9e93acbeefb11de15f86290861"`);
        await queryRunner.query(`ALTER TABLE "paiement_redevance" DROP CONSTRAINT "FK_e87bc00627bab8c715344b3e1ef"`);
        await queryRunner.query(`ALTER TABLE "paiement_redevance" DROP CONSTRAINT "FK_5b97f3e1b54a2de30841e3e2b55"`);
        await queryRunner.query(`ALTER TABLE "presence" DROP CONSTRAINT "FK_11aec335fadcdd040b91b7e39d5"`);
        await queryRunner.query(`ALTER TABLE "presence" DROP CONSTRAINT "FK_86c761a5794b7ca87a49987d2ec"`);
        await queryRunner.query(`ALTER TABLE "presence" DROP CONSTRAINT "FK_74b42bd3588c31e1ba501245922"`);
        await queryRunner.query(`ALTER TABLE "quittance" DROP CONSTRAINT "FK_6b50a171eb461487588a6373a5d"`);
        await queryRunner.query(`ALTER TABLE "quittance" DROP CONSTRAINT "FK_3f3908ae878466f22b0f26ebcff"`);
        await queryRunner.query(`ALTER TABLE "recette" DROP CONSTRAINT "FK_36c676f53129d6df971a4d8a5d3"`);
        await queryRunner.query(`ALTER TABLE "recette" DROP CONSTRAINT "FK_e7336902897fad254482f7ba731"`);
        await queryRunner.query(`ALTER TABLE "redevance" DROP CONSTRAINT "FK_f71f211f9f369783c263f949383"`);
        await queryRunner.query(`ALTER TABLE "redevance" DROP CONSTRAINT "FK_c58c9419e1f2fece73912b96983"`);
        await queryRunner.query(`ALTER TABLE "redevance" DROP CONSTRAINT "FK_d3a1cc96631a07a15638cb30288"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP CONSTRAINT "FK_27e2c16ce312e57b57534f2c9c3"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP CONSTRAINT "FK_e114bfbd4a9e15f84b44ca20cc4"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP CONSTRAINT "FK_218b09df03e359e3cc13e724137"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_11b213ae69c7dcdeb03cf173300"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_333bf7319119e9aaee9355bb599"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_036009d041bb77a3cb22ccfb885"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_f6f64961aef6a951a955440b251"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_eface4ddda53819e035e0fe3d0b"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_955abfa6affa003c4089bb758bc"`);
        await queryRunner.query(`ALTER TABLE "tarif" DROP CONSTRAINT "FK_51247cc1b452e66fce38d16b315"`);
        await queryRunner.query(`ALTER TABLE "type_droit" DROP CONSTRAINT "FK_2c9503133131d84c7d03c88a639"`);
        await queryRunner.query(`ALTER TABLE "zone" DROP CONSTRAINT "FK_2fb8e047bb273972f5b2b3fff0f"`);
        await queryRunner.query(`ALTER TABLE "marche" DROP CONSTRAINT "FK_0c7a38243b5e2e1c0d8691b6d85"`);
        await queryRunner.query(`ALTER TABLE "distribution_zone" DROP CONSTRAINT "FK_14be07e38224a638d1e6817970f"`);
        await queryRunner.query(`ALTER TABLE "local" DROP CONSTRAINT "FK_7dc68186f210b336ef0729e8f00"`);
        await queryRunner.query(`ALTER TABLE "local" DROP CONSTRAINT "FK_4e8523a7a7be0e4c8f0f8d87483"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_313ee835847f09171f2388edfd7"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_42047a721a672b9bb58bab4e4c0"`);
        await queryRunner.query(`ALTER TABLE "commercant" DROP CONSTRAINT "FK_52298195bfa471ebb106a372205"`);
        await queryRunner.query(`ALTER TABLE "paiement_location" DROP CONSTRAINT "FK_06ba8fa8cfc78122d47e69d6ace"`);
        await queryRunner.query(`ALTER TABLE "paiement_location" DROP CONSTRAINT "FK_e9dacf4b263bba19661503c6467"`);
        await queryRunner.query(`ALTER TABLE "paiement" DROP CONSTRAINT "FK_b007bba65d9f9c530719a2e9917"`);
        await queryRunner.query(`ALTER TABLE "paiement" DROP CONSTRAINT "FK_fe61685939535671e26808d848e"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_affectation_commercant_local_debut"`);
        await queryRunner.query(`DROP INDEX "public"."IX_affectation_local"`);
        await queryRunner.query(`DROP INDEX "public"."IX_affectation_commercant"`);
        await queryRunner.query(`DROP TABLE "affectation"`);
        await queryRunner.query(`DROP INDEX "public"."IX_audit_log_table_record"`);
        await queryRunner.query(`DROP INDEX "public"."IX_audit_log_created"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "controle"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_paiement_redevance"`);
        await queryRunner.query(`DROP TABLE "paiement_redevance"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_parametre_cle_portee_scope"`);
        await queryRunner.query(`DROP TABLE "parametre"`);
        await queryRunner.query(`DROP INDEX "public"."IX_presence_commercant_date"`);
        await queryRunner.query(`DROP INDEX "public"."IX_presence_zone_date"`);
        await queryRunner.query(`DROP TABLE "presence"`);
        await queryRunner.query(`DROP TABLE "quittance"`);
        await queryRunner.query(`DROP TABLE "recette"`);
        await queryRunner.query(`DROP TABLE "redevance"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_echeance_periode"`);
        await queryRunner.query(`DROP TABLE "echeance"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_droit"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_zone"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_marche"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_local"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_typelocal"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_activite"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_periodicite"`);
        await queryRunner.query(`DROP INDEX "public"."IX_tarif_dates"`);
        await queryRunner.query(`DROP TABLE "tarif"`);
        await queryRunner.query(`DROP TABLE "type_droit"`);
        await queryRunner.query(`DROP TABLE "periodicite"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_sigrnf_sync_event_reference"`);
        await queryRunner.query(`DROP TABLE "sigrnf_sync"`);
        await queryRunner.query(`DROP TYPE "public"."sigrnf_sync_status_enum"`);
        await queryRunner.query(`DROP TABLE "zone"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_marche_commune_nom"`);
        await queryRunner.query(`DROP TABLE "marche"`);
        await queryRunner.query(`DROP TABLE "commune"`);
        await queryRunner.query(`DROP TABLE "distribution_zone"`);
        await queryRunner.query(`DROP TABLE "local"`);
        await queryRunner.query(`DROP TYPE "public"."local_statut_enum"`);
        await queryRunner.query(`DROP TABLE "type_locale"`);
        await queryRunner.query(`DROP TYPE "public"."type_locale_type_contrat_enum"`);
        await queryRunner.query(`DROP TABLE "location"`);
        await queryRunner.query(`DROP TYPE "public"."location_periodicite_enum"`);
        await queryRunner.query(`DROP TABLE "commercant"`);
        await queryRunner.query(`DROP TABLE "activite_commerciale"`);
        await queryRunner.query(`DROP TABLE "paiement_location"`);
        await queryRunner.query(`DROP TABLE "paiement"`);
        await queryRunner.query(`DROP TYPE "public"."paiement_status_enum"`);
        await queryRunner.query(`DROP TABLE "agent"`);
        await queryRunner.query(`DROP TABLE "mode_paiement"`);
    }

}
